version: '3'

services:
  flask_app:
    container_name: flask_app
    build: 
      context: ..
      dockerfile: Dockerfile
    restart: on-failure
    command: python3
    ports: 
      - '80:5000'
    stdin_open: true
    tty: true
    